/**
 * test_ui_filter.js
 * Tests the browser-side filter() logic used in index.html (generated by generate_html.js).
 * Run: node src/tests/test_ui_filter.js
 *
 * REGRESSION COVERAGE:
 * - Null/undefined crash protection
 * - Decimal price parsing ($262.50)
 * - Multi-price ranges ($150 / $600)
 * - Corrupted comma-only cost strings (LSU-style: ", , , ")
 * - Below-floor prices < $100 (Illinois: $59.99, West Texas A&M: $50)
 * - TBA/Contact for pricing detection
 * - over500 / underXXX tier matching
 */

function simulateFilter(cost, costFilter) {
  if (costFilter === "all") return true;

  // Mirror EXACT logic from generate_html.js filter() function
  const c = cost || "";
  const priceMatches = c.match(/\d+[\d,]*(?:\.\d+)?/g);
  const prices = priceMatches
    ? priceMatches.map((m) => parseFloat(m.replace(/,/g, "")))
    : [0];
  const maxPrice = Math.max(...prices);
  const validPrices = prices.filter((p) => p > 0);
  const minPrice = validPrices.length > 0 ? Math.min(...validPrices) : 0;

  let matchesCost = true;
  if (costFilter === "under150") matchesCost = minPrice > 0 && minPrice < 150;
  else if (costFilter === "under200")
    matchesCost = minPrice > 0 && minPrice < 200;
  else if (costFilter === "under250")
    matchesCost = minPrice > 0 && minPrice < 250;
  else if (costFilter === "under300")
    matchesCost = minPrice > 0 && minPrice < 300;
  else if (costFilter === "under350")
    matchesCost = minPrice > 0 && minPrice < 350;
  else if (costFilter === "under500")
    matchesCost = minPrice > 0 && minPrice < 500;
  else if (costFilter === "over500") matchesCost = maxPrice >= 500;
  else if (costFilter === "tba")
    matchesCost =
      maxPrice === 0 ||
      c.toLowerCase().includes("tba") ||
      c.toLowerCase().includes("contact");

  return matchesCost;
}

const tests = [
  // --- Basic tier matching ---
  {
    desc: "Basic: $100 under150",
    cost: "$100",
    filter: "under150",
    expected: true,
  },
  {
    desc: "Basic: $200 under200",
    cost: "$200",
    filter: "under200",
    expected: false,
  }, // not UNDER 200
  {
    desc: "Basic: $199 under200",
    cost: "$199",
    filter: "under200",
    expected: true,
  },
  {
    desc: "Basic: $600 over500",
    cost: "$600",
    filter: "over500",
    expected: true,
  },
  {
    desc: "Basic: $499 over500",
    cost: "$499",
    filter: "over500",
    expected: false,
  },

  // --- Decimal parsing (original bug) ---
  {
    desc: "Decimal: $262.50 not over500",
    cost: "$262.50",
    filter: "over500",
    expected: false,
  },
  {
    desc: "Decimal: $262.50 under300",
    cost: "$262.50",
    filter: "under300",
    expected: true,
  },

  // --- Multi-price ranges ---
  {
    desc: "Range: $150/$600 over500",
    cost: "$150 / $600",
    filter: "over500",
    expected: true,
  },
  {
    desc: "Range: $150/$600 under200",
    cost: "$150 / $600",
    filter: "under200",
    expected: true,
  }, // min=150 < 200
  {
    desc: "Range: $300/$500 over500",
    cost: "$300 / $500",
    filter: "over500",
    expected: true,
  },
  {
    desc: "Range: $300/$499 not over500",
    cost: "$300 / $499",
    filter: "over500",
    expected: false,
  },

  // --- TBA / No price ---
  {
    desc: "TBA: explicit TBA string",
    cost: "TBA",
    filter: "under150",
    expected: false,
  },
  {
    desc: "TBA: filter=tba matches TBA",
    cost: "TBA",
    filter: "tba",
    expected: true,
  },
  {
    desc: "TBA: contact for pricing",
    cost: "Contact for pricing",
    filter: "tba",
    expected: true,
  },
  {
    desc: "TBA: contact match",
    cost: "Contact",
    filter: "under150",
    expected: false,
  },

  // --- Null/Undefined crash protection ---
  {
    desc: "Crash: null cost under150",
    cost: null,
    filter: "under150",
    expected: false,
  },
  {
    desc: "Crash: undefined cost under150",
    cost: undefined,
    filter: "under150",
    expected: false,
  },
  {
    desc: "Crash: empty string under150",
    cost: "",
    filter: "under150",
    expected: false,
  },

  // --- REGRESSION: LSU-style corrupted cost ", , , " ---
  {
    desc: 'LSU Bug: ", , , " not under150',
    cost: ", , , ",
    filter: "under150",
    expected: false,
  },
  {
    desc: 'LSU Bug: ", , , " = tba',
    cost: ", , , ",
    filter: "tba",
    expected: true,
  },
  {
    desc: 'LSU Bug: ", , , " not over500',
    cost: ", , , ",
    filter: "over500",
    expected: false,
  },

  // --- REGRESSION: Below-floor prices (Illinois $59.99, West TX $50) ---
  // After fix these are null in the DB, but we test the filter logic handles them correctly too
  {
    desc: "Floor: $59.99 matches under150",
    cost: "$59.99",
    filter: "under150",
    expected: true,
  },
  {
    desc: "Floor: $59.99 not over500",
    cost: "$59.99",
    filter: "over500",
    expected: false,
  },
  {
    desc: "Floor: $50 matches under150",
    cost: "$50",
    filter: "under150",
    expected: true,
  },
  {
    desc: "Floor: $50 treated as tba?",
    cost: "$50",
    filter: "tba",
    expected: false,
  }, // it HAS a price
  {
    desc: "Floor: $1 matches under150",
    cost: "$1",
    filter: "under150",
    expected: true,
  },
  {
    desc: "Floor: $1 treated as tba?",
    cost: "$1",
    filter: "tba",
    expected: false,
  },

  // --- Edge cases ---
  {
    desc: "Edge: $500 exactly over500",
    cost: "$500",
    filter: "over500",
    expected: true,
  },
  {
    desc: "Edge: $500 not under500",
    cost: "$500",
    filter: "under500",
    expected: false,
  },
  {
    desc: "Edge: $149.99 under150",
    cost: "$149.99",
    filter: "under150",
    expected: true,
  },
  {
    desc: "Edge: $150 not under150",
    cost: "$150",
    filter: "under150",
    expected: false,
  },
  {
    desc: "Edge: all filter always true",
    cost: null,
    filter: "all",
    expected: true,
  },
  {
    desc: "Edge: comma price $1,200",
    cost: "$1,200",
    filter: "over500",
    expected: true,
  },
];

console.log("--- UI Filter Logic Regression Test ---\n");
let failed = 0;
let passed = 0;

tests.forEach((t, i) => {
  try {
    const result = simulateFilter(t.cost, t.filter);
    const ok = result === t.expected;
    if (ok) {
      console.log(`✅ [${String(i).padStart(2)}] ${t.desc}`);
      passed++;
    } else {
      console.log(`❌ [${String(i).padStart(2)}] ${t.desc}`);
      console.log(
        `        cost=${JSON.stringify(t.cost)}, filter=${t.filter} → Expected: ${t.expected}, Got: ${result}`,
      );
      failed++;
    }
  } catch (e) {
    console.log(
      `💥 [${String(i).padStart(2)}] ${t.desc} → CRASHED: ${e.message}`,
    );
    failed++;
  }
});

console.log(`\n${"─".repeat(50)}`);
if (failed === 0) {
  console.log(`✅ All ${passed} filter tests passed!`);
} else {
  console.log(`❌ ${failed}/${tests.length} tests FAILED.`);
  process.exit(1);
}
