const fs = require("fs");

// The skeletal data from merge_data.js
const teams = [
  "Abilene Christian",
  "Air Force",
  "Akron",
  "Alabama",
  "Alabama A&M",
  "Alabama State",
  "Albany",
  "Alcorn State",
  "Appalachian State",
  "Arizona",
  "Arizona State",
  "Arkansas",
  "Arkansas State",
  "Arkansas-Pine Bluff",
  "Army",
  "Auburn",
  "Austin Peay",
  "Ball State",
  "Baylor",
  "Bellarmine",
  "Belmont",
  "Bethune-Cookman",
  "Binghamton",
  "Boston College",
  "Bowling Green",
  "Bradley",
  "Brown",
  "Bryant",
  "Bucknell",
  "Butler",
  "BYU",
  "Cal Poly",
  "Cal State Bakersfield",
  "Cal State Fullerton",
  "Cal State Northridge",
  "California",
  "California Baptist",
  "Campbell",
  "Canisius",
  "Central Arkansas",
  "Central Connecticut",
  "Central Michigan",
  "Charleston",
  "Charleston Southern",
  "Charlotte",
  "Cincinnati",
  "Clemson",
  "Coastal Carolina",
  "Columbia",
  "Connecticut",
  "Coppin State",
  "Cornell",
  "Creighton",
  "Dallas Baptist",
  "Dartmouth",
  "Davidson",
  "Dayton",
  "Delaware",
  "Delaware State",
  "Duke",
  "East Carolina",
  "East Tennessee State",
  "Eastern Illinois",
  "Eastern Kentucky",
  "Eastern Michigan",
  "Elon",
  "Evansville",
  "Fairfield",
  "Fairleigh Dickinson",
  "FAU",
  "FGCU",
  "FIU",
  "Florida",
  "Florida A&M",
  "Florida State",
  "Fordham",
  "Fresno State",
  "Gardner-Webb",
  "George Mason",
  "George Washington",
  "Georgetown",
  "Georgia",
  "Georgia Southern",
  "Georgia State",
  "Georgia Tech",
  "Gonzaga",
  "Grambling State",
  "Grand Canyon",
  "Harvard",
  "Hawaii",
  "High Point",
  "Hofstra",
  "Holy Cross",
  "Houston",
  "Houston Christian",
  "Illinois",
  "Illinois State",
  "Incarnate Word",
  "Indiana",
  "Indiana State",
  "Iona",
  "Iowa",
  "Jackson State",
  "Jacksonville",
  "Jacksonville State",
  "James Madison",
  "Kansas",
  "Kansas State",
  "Kennesaw State",
  "Kent State",
  "Kentucky",
  "La Salle",
  "Lafayette",
  "Lamar",
  "Le Moyne",
  "Lehigh",
  "Liberty",
  "Lindenwood",
  "Lipscomb",
  "Little Rock",
  "Long Beach State",
  "Long Island",
  "Longwood",
  "Louisiana",
  "Louisiana Tech",
  "Louisville",
  "Loyola-Marymount",
  "LSU",
  "Maine",
  "Manhattan",
  "Marist",
  "Marshall",
  "Maryland",
  "Maryland Eastern Shore",
  "McNeese",
  "Memphis",
  "Mercer",
  "Mercyhurst",
  "Merrimack",
  "Miami (FL)",
  "Miami (OH)",
  "Michigan",
  "Michigan State",
  "Middle Tennessee",
  "Milwaukee",
  "Minnesota",
  "Mississippi State",
  "Mississippi Valley State",
  "Missouri",
  "Missouri State",
  "Monmouth",
  "Morehead State",
  "Mount Saint Mary's",
  "Murray State",
  "Navy",
  "Nebraska",
  "Nevada",
  "New Haven",
  "New Mexico",
  "New Mexico State",
  "New Orleans",
  "Niagara",
  "Nicholls",
  "NJIT",
  "Norfolk State",
  "North Alabama",
  "North Carolina",
  "North Carolina A&T",
  "North Carolina State",
  "North Dakota State",
  "North Florida",
  "Northeastern",
  "Northern Colorado",
  "Northern Illinois",
  "Northern Kentucky",
  "Northwestern",
  "Northwestern State",
  "Notre Dame",
  "Oakland",
  "Ohio",
  "Ohio State",
  "Oklahoma",
  "Oklahoma State",
  "Old Dominion",
  "Ole Miss",
  "Omaha",
  "Oral Roberts",
  "Oregon",
  "Oregon State",
  "Pacific",
  "Penn",
  "Penn State",
  "Pepperdine",
  "Pittsburgh",
  "Portland",
  "Prairie View A&M",
  "Presbyterian College",
  "Princeton",
  "Purdue",
  "Queens",
  "Quinnipiac",
  "Radford",
  "Rhode Island",
  "Rice",
  "Richmond",
  "Rider",
  "Rutgers",
  "Sacramento State",
  "Sacred Heart",
  "Saint Bonaventure",
  "Saint John's",
  "Saint Joseph's",
  "Saint Louis",
  "Saint Mary's College",
  "Saint Peter's",
  "Saint Thomas",
  "Sam Houston State",
  "Samford",
  "San Diego",
  "San Diego State",
  "San Francisco",
  "San Jose State",
  "Santa Clara",
  "Seattle University",
  "Seton Hall",
  "Siena",
  "SIUE",
  "South Alabama",
  "South Carolina",
  "South Carolina Upstate",
  "South Dakota State",
  "South Florida",
  "Southeast Missouri",
  "Southeastern Louisiana",
  "Southern",
  "Southern Illinois",
  "Southern Indiana",
  "Southern Miss",
  "Stanford",
  "Stephen F. Austin",
  "Stetson",
  "Stonehill",
  "Stony Brook",
  "Tarleton State",
  "TCU",
  "Tennessee",
  "Tennessee Tech",
  "Tennessee-Martin",
  "Texas",
  "Texas A&M",
  "Texas A&M-Corpus Christi",
  "Texas Southern",
  "Texas State",
  "Texas Tech",
  "The Citadel",
  "Toledo",
  "Towson",
  "Troy",
  "Tulane",
  "UAB",
  "UC Davis",
  "UC Irvine",
  "UC Riverside",
  "UC San Diego",
  "UC Santa Barbara",
  "UCF",
  "UCLA",
  "UIC",
  "ULM",
  "UMass",
  "UMass-Lowell",
  "UMBC",
  "UNC Asheville",
  "UNCG",
  "UNCW",
  "UNLV",
  "USC",
  "UTA",
  "Utah",
  "Utah Tech",
  "Utah Valley",
  "UTRGV",
  "UTSA",
  "Valparaiso",
  "Vanderbilt",
  "VCU",
  "Villanova",
  "Virginia",
  "Virginia Tech",
  "VMI",
  "Wagner",
  "Wake Forest",
  "Washington",
  "Washington State",
  "West Georgia",
  "West Virginia",
  "Western Carolina",
  "Western Illinois",
  "Western Kentucky",
  "Western Michigan",
  "Wichita State",
  "William & Mary",
  "Winthrop",
  "Wofford",
  "Wright State",
  "Xavier",
  "Yale",
  "Youngstown State",
];

// Current compiled data
const data = JSON.parse(fs.readFileSync("camps_data.json", "utf8"));
const currentUniversities = data.map((d) => d.university.toLowerCase());

const missing = teams.filter((t) => {
  return !currentUniversities.some(
    (cu) => cu.includes(t.toLowerCase()) || t.toLowerCase().includes(cu),
  );
});

console.log("Missing Programs (" + missing.length + "):");
missing.forEach((m) => console.log("- " + m));
