const fs = require("fs");

// Master list (308 programs)
const teams = [
  "Abilene Christian",
  "Air Force",
  "Akron",
  "Alabama",
  "Alabama A&M",
  "Alabama State",
  "Albany",
  "Alcorn State",
  "Appalachian State",
  "Arizona",
  "Arizona State",
  "Arkansas",
  "Arkansas State",
  "Arkansas-Pine Bluff",
  "Army",
  "Auburn",
  "Austin Peay",
  "Ball State",
  "Baylor",
  "Bellarmine",
  "Belmont",
  "Bethune-Cookman",
  "Binghamton",
  "Boston College",
  "Bowling Green",
  "Bradley",
  "Brown",
  "Bryant",
  "Bucknell",
  "Butler",
  "BYU",
  "Cal Poly",
  "Cal State Bakersfield",
  "Cal State Fullerton",
  "Cal State Northridge",
  "California",
  "California Baptist",
  "Campbell",
  "Canisius",
  "Central Arkansas",
  "Central Connecticut",
  "Central Michigan",
  "Charleston",
  "Charleston Southern",
  "Charlotte",
  "Cincinnati",
  "Clemson",
  "Coastal Carolina",
  "Columbia",
  "Connecticut",
  "Coppin State",
  "Cornell",
  "Creighton",
  "Dallas Baptist",
  "Dartmouth",
  "Davidson",
  "Dayton",
  "Delaware",
  "Delaware State",
  "Duke",
  "East Carolina",
  "East Tennessee State",
  "Eastern Illinois",
  "Eastern Kentucky",
  "Eastern Michigan",
  "Elon",
  "Evansville",
  "Fairfield",
  "Fairleigh Dickinson",
  "FAU",
  "FGCU",
  "FIU",
  "Florida",
  "Florida A&M",
  "Florida State",
  "Fordham",
  "Fresno State",
  "Gardner-Webb",
  "George Mason",
  "George Washington",
  "Georgetown",
  "Georgia",
  "Georgia Southern",
  "Georgia State",
  "Georgia Tech",
  "Gonzaga",
  "Grambling State",
  "Grand Canyon",
  "Harvard",
  "Hawaii",
  "High Point",
  "Hofstra",
  "Holy Cross",
  "Houston",
  "Houston Christian",
  "Illinois",
  "Illinois State",
  "Incarnate Word",
  "Indiana",
  "Indiana State",
  "Iona",
  "Iowa",
  "Jackson State",
  "Jacksonville",
  "Jacksonville State",
  "James Madison",
  "Kansas",
  "Kansas State",
  "Kennesaw State",
  "Kent State",
  "Kentucky",
  "La Salle",
  "Lafayette",
  "Lamar",
  "Le Moyne",
  "Lehigh",
  "Liberty",
  "Lindenwood",
  "Lipscomb",
  "Little Rock",
  "Long Beach State",
  "Long Island",
  "Longwood",
  "Louisiana",
  "Louisiana Tech",
  "Louisville",
  "Loyola-Marymount",
  "LSU",
  "Maine",
  "Manhattan",
  "Marist",
  "Marshall",
  "Maryland",
  "Maryland Eastern Shore",
  "McNeese",
  "Memphis",
  "Mercer",
  "Mercyhurst",
  "Merrimack",
  "Miami (FL)",
  "Miami (OH)",
  "Michigan",
  "Michigan State",
  "Middle Tennessee",
  "Milwaukee",
  "Minnesota",
  "Mississippi State",
  "Mississippi Valley State",
  "Missouri",
  "Missouri State",
  "Monmouth",
  "Morehead State",
  "Mount Saint Mary's",
  "Murray State",
  "Navy",
  "Nebraska",
  "Nevada",
  "New Haven",
  "New Mexico",
  "New Mexico State",
  "New Orleans",
  "Niagara",
  "Nicholls",
  "NJIT",
  "Norfolk State",
  "North Alabama",
  "North Carolina",
  "North Carolina A&T",
  "North Carolina State",
  "North Dakota State",
  "North Florida",
  "Northeastern",
  "Northern Colorado",
  "Northern Illinois",
  "Northern Kentucky",
  "Northwestern",
  "Northwestern State",
  "Notre Dame",
  "Oakland",
  "Ohio",
  "Ohio State",
  "Oklahoma",
  "Oklahoma State",
  "Old Dominion",
  "Ole Miss",
  "Omaha",
  "Oral Roberts",
  "Oregon",
  "Oregon State",
  "Pacific",
  "Penn",
  "Penn State",
  "Pepperdine",
  "Pittsburgh",
  "Portland",
  "Prairie View A&M",
  "Presbyterian College",
  "Princeton",
  "Purdue",
  "Queens",
  "Quinnipiac",
  "Radford",
  "Rhode Island",
  "Rice",
  "Richmond",
  "Rider",
  "Rutgers",
  "Sacramento State",
  "Sacred Heart",
  "Saint Bonaventure",
  "Saint John's",
  "Saint Joseph's",
  "Saint Louis",
  "Saint Mary's College",
  "Saint Peter's",
  "Saint Thomas",
  "Sam Houston State",
  "Samford",
  "San Diego",
  "San Diego State",
  "San Francisco",
  "San Jose State",
  "Santa Clara",
  "Seattle University",
  "Seton Hall",
  "Siena",
  "SIUE",
  "South Alabama",
  "South Carolina",
  "South Carolina Upstate",
  "South Dakota State",
  "South Florida",
  "Southeast Missouri",
  "Southeastern Louisiana",
  "Southern",
  "Southern Illinois",
  "Southern Indiana",
  "Southern Miss",
  "Stanford",
  "Stephen F. Austin",
  "Stetson",
  "Stonehill",
  "Stony Brook",
  "Tarleton State",
  "TCU",
  "Tennessee",
  "Tennessee Tech",
  "Tennessee-Martin",
  "Texas",
  "Texas A&M",
  "Texas A&M-Corpus Christi",
  "Texas Southern",
  "Texas State",
  "Texas Tech",
  "The Citadel",
  "Toledo",
  "Towson",
  "Troy",
  "Tulane",
  "UAB",
  "UC Davis",
  "UC Irvine",
  "UC Riverside",
  "UC San Diego",
  "UC Santa Barbara",
  "UCF",
  "UCLA",
  "UIC",
  "ULM",
  "UMass",
  "UMass-Lowell",
  "UMBC",
  "UNC Asheville",
  "UNCG",
  "UNCW",
  "UNLV",
  "USC",
  "UTA",
  "Utah",
  "Utah Tech",
  "Utah Valley",
  "UTRGV",
  "UTSA",
  "Valparaiso",
  "Vanderbilt",
  "VCU",
  "Villanova",
  "Virginia",
  "Virginia Tech",
  "VMI",
  "Wagner",
  "Wake Forest",
  "Washington",
  "Washington State",
  "West Georgia",
  "West Virginia",
  "Western Carolina",
  "Western Illinois",
  "Western Kentucky",
  "Western Michigan",
  "Wichita State",
  "William & Mary",
  "Winthrop",
  "Wofford",
  "Wright State",
  "Xavier",
  "Yale",
  "Youngstown State",
];

const coaches = JSON.parse(
  fs
    .readFileSync("merge_data.js", "utf8")
    .match(/const coaches = ({.*?});/s)[1],
);

// Current parsed data from markdown table
const currentData = JSON.parse(fs.readFileSync("camps_data.json", "utf8"));

// Verified ones from parse_and_merge.js
const manuallyVerified = [
  {
    university: "Alabama",
    campUrl: "https://www.alabamabaseballcamps.com/",
    dates: "Jun 15-18 / Jul 12-14 / Jul 27-30, 2026",
    cost: "$262.50 Youth / $1,312.50 Elite",
    details: "Elite & Youth Camps at Sewell-Thomas Stadium.",
    contact: "Rob Vaughn (Head Coach)",
    division: "DI",
    address:
      "Sewell-Thomas Stadium, 241 Paul W Bryant Dr, Tuscaloosa, AL 35401",
    whatToBring:
      "Helmet, Bat, Batting Gloves, Glove, Cleats and turf shoes. Clearly marked with player's name.",
  },
  {
    university: "Florida",
    campUrl:
      "https://floridagators.com/sports/2026/2/18/baseball-summer-showcase-camp",
    dates: "Jul 12, 2026 / Jul 26, 2026",
    cost: "$250",
    details: "Summer Showcase Camp at Condron Ballpark.",
    contact: "Kevin O'Sullivan (Head Coach)",
    division: "DI",
    address: "Condron Ballpark, 2800 Citrus Road, Gainesville, FL 32608",
    whatToBring: "Position specific instruction. Bring own baseball equipment.",
  },
  {
    university: "Ole Miss",
    campUrl: "https://baseball.olemisssportscamps.com/",
    dates: "Jun 22-25 / Jul 13-16 / Jul 20-23, 2026",
    cost: "$341.25",
    details: "Summer Baseball Camps at Swayze Field.",
    contact: "Mike Bianco (Head Coach)",
    division: "DI",
    address: "Swayze Field, 101 Swayze Ln, University, MS 38677",
    whatToBring: "Baseball equipment, clearly marked with name.",
  },
];

const finalData = teams.map((univ) => {
  // Check if we have verified info
  const mv = manuallyVerified.find((m) => m.university === univ);
  if (mv) return mv;

  // Check if we have current data
  const cd = currentData.find(
    (c) =>
      c.university.toLowerCase().includes(univ.toLowerCase()) ||
      univ.toLowerCase().includes(c.university.toLowerCase()),
  );
  if (cd) {
    return {
      ...cd,
      university: univ, // Standardizing to master list name
      contact: cd.contact || coaches[univ] || "Not Listed",
      address: cd.address || "On-campus facility",
      whatToBring: cd.whatToBring || "Equipment and standard items.",
    };
  }

  // Default skeletal entry
  return {
    university: univ,
    campUrl: "",
    dates: "TBA",
    cost: "TBA",
    details: "No 2026 camps posted as of April 2, 2026",
    contact: coaches[univ] || "Not Listed",
    division: "DI",
    address: "On-campus facility",
    whatToBring:
      "Glove, bat, helmet, cleats, baseball pants, water bottle, sunscreen.",
  };
});

fs.writeFileSync("camps_data.json", JSON.stringify(finalData, null, 2));
console.log(`Finalized database with ${finalData.length} programs.`);
