// ═══════════════════════════════════════════════════════════════
//  NCAA Baseball Programs — Official Mascot/Nickname Lookup
//  Used to build intelligent search queries:
//    "Arkansas Razorbacks baseball camp 2026"
//  instead of the garbage:
//    "Arkansas" uasys baseball camp 2026
// ═══════════════════════════════════════════════════════════════

const MASCOT_LOOKUP = {
  // ── D1 Power Conference Programs ──────────────────────────
  'Alabama': 'Crimson Tide',
  'Arizona': 'Wildcats',
  'Arizona State': 'Sun Devils',
  'Arkansas': 'Razorbacks',
  'Arkansas State': 'Red Wolves',
  'Arkansas-Pine Bluff': 'Golden Lions',
  'Auburn': 'Tigers',
  'Baylor': 'Bears',
  'BYU': 'Cougars',
  'California': 'Golden Bears',
  'Clemson': 'Tigers',
  'Connecticut': 'Huskies',
  'Duke': 'Blue Devils',
  'Florida': 'Gators',
  'Florida State': 'Seminoles',
  'Georgia': 'Bulldogs',
  'Georgia Tech': 'Yellow Jackets',
  'Houston': 'Cougars',
  'Illinois': 'Fighting Illini',
  'Indiana': 'Hoosiers',
  'Iowa': 'Hawkeyes',
  'Kansas': 'Jayhawks',
  'Kansas State': 'Wildcats',
  'Kentucky': 'Wildcats',
  'LSU': 'Tigers',
  'Louisville': 'Cardinals',
  'Maryland': 'Terrapins',
  'Michigan': 'Wolverines',
  'Michigan State': 'Spartans',
  'Minnesota': 'Golden Gophers',
  'Mississippi State': 'Bulldogs',
  'Missouri': 'Tigers',
  'Nebraska': 'Cornhuskers',
  'North Carolina': 'Tar Heels',
  'North Carolina State': 'Wolfpack',
  'Northwestern': 'Wildcats',
  'Notre Dame': 'Fighting Irish',
  'Ohio State': 'Buckeyes',
  'Oklahoma': 'Sooners',
  'Oklahoma State': 'Cowboys',
  'Ole Miss': 'Rebels',
  'Oregon': 'Ducks',
  'Oregon State': 'Beavers',
  'Penn State': 'Nittany Lions',
  'Pittsburgh': 'Panthers',
  'Purdue': 'Boilermakers',
  'Rutgers': 'Scarlet Knights',
  'South Carolina': 'Gamecocks',
  'Stanford': 'Cardinal',
  'TCU': 'Horned Frogs',
  'Tennessee': 'Volunteers',
  'Texas': 'Longhorns',
  'Texas A&M': 'Aggies',
  'Texas Tech': 'Red Raiders',
  'UCLA': 'Bruins',
  'USC': 'Trojans',
  'Utah': 'Utes',
  'Vanderbilt': 'Commodores',
  'Virginia': 'Cavaliers',
  'Virginia Tech': 'Hokies',
  'Wake Forest': 'Demon Deacons',
  'Washington': 'Huskies',
  'Washington State': 'Cougars',
  'West Virginia': 'Mountaineers',

  // ── D1 Mid-Major Programs ─────────────────────────────────
  'Abilene Christian': 'Wildcats',
  'Air Force': 'Falcons',
  'Akron': 'Zips',
  'Alabama A&M': 'Bulldogs',
  'Alabama State': 'Hornets',
  'Albany': 'Great Danes',
  'Alcorn State': 'Braves',
  'Appalachian State': 'Mountaineers',
  'Army': 'Black Knights',
  'Austin Peay': 'Governors',
  'Ball State': 'Cardinals',
  'Bellarmine': 'Knights',
  'Belmont': 'Bruins',
  'Bethune-Cookman': 'Wildcats',
  'Binghamton': 'Bearcats',
  'Boston College': 'Eagles',
  'Bowling Green': 'Falcons',
  'Bradley': 'Braves',
  'Brown': 'Bears',
  'Bryant': 'Bulldogs',
  'Bucknell': 'Bison',
  'Butler': 'Bulldogs',
  'Cal Poly': 'Mustangs',
  'Cal State Bakersfield': 'Roadrunners',
  'Cal State Fullerton': 'Titans',
  'Cal State Northridge': 'Matadors',
  'California Baptist': 'Lancers',
  'Campbell': 'Fighting Camels',
  'Canisius': 'Golden Griffins',
  'Central Arkansas': 'Bears',
  'Central Connecticut': 'Blue Devils',
  'Central Michigan': 'Chippewas',
  'Charleston': 'Cougars',
  'Charleston Southern': 'Buccaneers',
  'Charlotte': '49ers',
  'Cincinnati': 'Bearcats',
  'Clemson': 'Tigers',
  'Coastal Carolina': 'Chanticleers',
  'Columbia': 'Lions',
  'Coppin State': 'Eagles',
  'Cornell': 'Big Red',
  'Creighton': 'Bluejays',
  'Dallas Baptist': 'Patriots',
  'Dartmouth': 'Big Green',
  'Davidson': 'Wildcats',
  'Dayton': 'Flyers',
  'Delaware': 'Blue Hens',
  'Delaware State': 'Hornets',
  'East Carolina': 'Pirates',
  'East Tennessee State': 'Buccaneers',
  'Eastern Illinois': 'Panthers',
  'Eastern Kentucky': 'Colonels',
  'Eastern Michigan': 'Eagles',
  'Elon': 'Phoenix',
  'Evansville': 'Purple Aces',
  'FAU': 'Owls',
  'FGCU': 'Eagles',
  'FIU': 'Panthers',
  'Fairfield': 'Stags',
  'Fairleigh Dickinson': 'Knights',
  'Florida A&M': 'Rattlers',
  'Fordham': 'Rams',
  'Fresno State': 'Bulldogs',
  'Gardner-Webb': 'Runnin\' Bulldogs',
  'George Mason': 'Patriots',
  'George Washington': 'Revolutionaries',
  'Georgetown': 'Hoyas',
  'Georgia Southern': 'Eagles',
  'Georgia State': 'Panthers',
  'Gonzaga': 'Bulldogs',
  'Grambling State': 'Tigers',
  'Grand Canyon': 'Lopes',
  'Harvard': 'Crimson',
  'Hawaii': 'Rainbow Warriors',
  'High Point': 'Panthers',
  'Hofstra': 'Pride',
  'Holy Cross': 'Crusaders',
  'Houston Christian': 'Huskies',
  'Illinois State': 'Redbirds',
  'Incarnate Word': 'Cardinals',
  'Indiana State': 'Sycamores',
  'Iona': 'Gaels',
  'Jackson State': 'Tigers',
  'Jacksonville': 'Dolphins',
  'Jacksonville State': 'Gamecocks',
  'James Madison': 'Dukes',
  'Kennesaw State': 'Owls',
  'Kent State': 'Golden Flashes',
  'La Salle': 'Explorers',
  'Lafayette': 'Leopards',
  'Lamar': 'Cardinals',
  'Le Moyne': 'Dolphins',
  'Lehigh': 'Mountain Hawks',
  'Liberty': 'Flames',
  'Lindenwood': 'Lions',
  'Lipscomb': 'Bisons',
  'Little Rock': 'Trojans',
  'Long Beach State': 'Beach',
  'Long Island': 'Sharks',
  'Longwood': 'Lancers',
  'Louisiana': 'Ragin\' Cajuns',
  'Louisiana Tech': 'Bulldogs',
  'Loyola-Marymount': 'Lions',
  'Maine': 'Black Bears',
  'Manhattan': 'Jaspers',
  'Marist': 'Red Foxes',
  'Marshall': 'Thundering Herd',
  'Maryland Eastern Shore': 'Hawks',
  'McNeese': 'Cowboys',
  'Memphis': 'Tigers',
  'Mercer': 'Bears',
  'Mercyhurst': 'Lakers',
  'Merrimack': 'Warriors',
  'Miami (FL)': 'Hurricanes',
  'Miami (OH)': 'RedHawks',
  'Middle Tennessee': 'Blue Raiders',
  'Milwaukee': 'Panthers',
  'Mississippi Valley State': 'Delta Devils',
  'Missouri State': 'Bears',
  'Monmouth': 'Hawks',
  'Morehead State': 'Eagles',
  'Mount Saint Mary\'s': 'Mountaineers',
  'Murray State': 'Racers',
  'NJIT': 'Highlanders',
  'Navy': 'Midshipmen',
  'Nevada': 'Wolf Pack',
  'New Mexico': 'Lobos',
  'New Mexico State': 'Aggies',
  'New Orleans': 'Privateers',
  'Niagara': 'Purple Eagles',
  'Nicholls': 'Colonels',
  'Norfolk State': 'Spartans',
  'North Alabama': 'Lions',
  'North Carolina A&T': 'Aggies',
  'North Dakota State': 'Bison',
  'North Florida': 'Ospreys',
  'Northeastern': 'Huskies',
  'Northern Colorado': 'Bears',
  'Northern Illinois': 'Huskies',
  'Northern Kentucky': 'Norse',
  'Northwestern State': 'Demons',
  'Oakland': 'Golden Grizzlies',
  'Ohio': 'Bobcats',
  'Oklahoma Baptist University': 'Bison',
  'Old Dominion': 'Monarchs',
  'Omaha': 'Mavericks',
  'Oral Roberts': 'Golden Eagles',
  'Pacific': 'Tigers',
  'Penn': 'Quakers',
  'Pepperdine': 'Waves',
  'Portland': 'Pilots',
  'Prairie View A&M': 'Panthers',
  'Presbyterian College': 'Blue Hose',
  'Princeton': 'Tigers',
  'Queens': 'Royals',
  'Quinnipiac': 'Bobcats',
  'Radford': 'Highlanders',
  'Rhode Island': 'Rams',
  'Rice': 'Owls',
  'Richmond': 'Spiders',
  'Rider': 'Broncs',
  'Sacramento State': 'Hornets',
  'Sacred Heart': 'Pioneers',
  'Saint Bonaventure': 'Bonnies',
  'Saint John\'s': 'Red Storm',
  'Saint Joseph\'s': 'Hawks',
  'Saint Louis': 'Billikens',
  'Saint Peter\'s': 'Peacocks',
  'Saint Thomas': 'Tommies',
  'Sam Houston State': 'Bearkats',
  'Samford': 'Bulldogs',
  'San Diego': 'Toreros',
  'San Diego State': 'Aztecs',
  'San Francisco': 'Dons',
  'San Jose State': 'Spartans',
  'Santa Clara': 'Broncos',
  'Seattle University': 'Redhawks',
  'Seton Hall': 'Pirates',
  'Siena': 'Saints',
  'South Alabama': 'Jaguars',
  'South Carolina Upstate': 'Spartans',
  'South Dakota State': 'Jackrabbits',
  'South Florida': 'Bulls',
  'Southeast Missouri': 'Redhawks',
  'Southeastern Louisiana': 'Lions',
  'Southern': 'Jaguars',
  'Southern Illinois': 'Salukis',
  'Southern Indiana': 'Screaming Eagles',
  'Southern Miss': 'Golden Eagles',
  'SIUE': 'Cougars',
  'Stephen F. Austin': 'Lumberjacks',
  'Stetson': 'Hatters',
  'Stonehill': 'Skyhawks',
  'Stony Brook': 'Seawolves',
  'Tarleton State': 'Texans',
  'Tennessee Tech': 'Golden Eagles',
  'Tennessee-Martin': 'Skyhawks',
  'Texas A&M-Corpus Christi': 'Islanders',
  'Texas Southern': 'Tigers',
  'Texas State': 'Bobcats',
  'The Citadel': 'Bulldogs',
  'Toledo': 'Rockets',
  'Towson': 'Tigers',
  'Troy': 'Trojans',
  'Tulane': 'Green Wave',
  'UAB': 'Blazers',
  'UC Davis': 'Aggies',
  'UC Irvine': 'Anteaters',
  'UC Riverside': 'Highlanders',
  'UC San Diego': 'Tritons',
  'UC Santa Barbara': 'Gauchos',
  'UCF': 'Knights',
  'UIC': 'Flames',
  'ULM': 'Warhawks',
  'UMBC': 'Retrievers',
  'UMass': 'Minutemen',
  'UMass-Lowell': 'River Hawks',
  'UNC Asheville': 'Bulldogs',
  'UNCG': 'Spartans',
  'UNCW': 'Seahawks',
  'UNLV': 'Rebels',
  'UTA': 'Mavericks',
  'UTRGV': 'Vaqueros',
  'UTSA': 'Roadrunners',
  'Utah Tech': 'Trailblazers',
  'Utah Valley': 'Wolverines',
  'VCU': 'Rams',
  'VMI': 'Keydets',
  'Valparaiso': 'Beacons',
  'Villanova': 'Wildcats',
  'Wagner': 'Seahawks',
  'Western Carolina': 'Catamounts',
  'Western Illinois': 'Leathernecks',
  'Western Kentucky': 'Hilltoppers',
  'Western Michigan': 'Broncos',
  'Wichita State': 'Shockers',
  'William & Mary': 'Tribe',
  'Winthrop': 'Eagles',
  'Wofford': 'Terriers',
  'Wright State': 'Raiders',
  'Xavier': 'Musketeers',
  'Yale': 'Bulldogs',
  'Youngstown State': 'Penguins',

  // ── D2 Programs ───────────────────────────────────────────
  'Academy of Art University': 'Urban Knights',
  'Adams State University': 'Grizzlies',
  'Adelphi University': 'Panthers',
  'Albany State University': 'Golden Rams',
  'American International College': 'Yellow Jackets',
  'Anderson University – South Carolina': 'Trojans',
  'Angelo State University': 'Rams',
  'Arkansas Tech University': 'Wonder Boys',
  'Ashland University': 'Eagles',
  'Assumption University': 'Greyhounds',
  'Auburn University – Montgomery': 'Warhawks',
  'Augusta University': 'Jaguars',
  'Augustana University – South Dakota': 'Vikings',
  'Azusa Pacific University': 'Cougars',
  'Barry University': 'Buccaneers',
  'Barton College': 'Bulldogs',
  'Belmont Abbey College': 'Crusaders',
  'Bemidji State University': 'Beavers',
  'Benedict College': 'Tigers',
  'Bentley University': 'Falcons',
  'Biola University': 'Eagles',
  'Bloomfield College': 'Bears',
  'Bloomsburg University of Pennsylvania': 'Huskies',
  'Bluefield State University': 'Big Blues',
  'Caldwell University': 'Cougars',
  'California State Polytechnic University – Pomona': 'Broncos',
  'California State University – Chico': 'Wildcats',
  'California State University – Dominguez Hills': 'Toros',
  'California State University – East Bay': 'Pioneers',
  'California State University – Los Angeles': 'Golden Eagles',
  'California State University – Monterey Bay': 'Otters',
  'California State University – San Bernardino': 'Coyotes',
  'California State University – San Marcos': 'Cougars',
  'California State University – Stanislaus': 'Warriors',
  'California University of Pennsylvania': 'Vulcans',
  'Cameron University': 'Aggies',
  'Carson-Newman University': 'Eagles',
  'Catawba College': 'Indians',
  'Cedarville University': 'Yellow Jackets',
  'Central Washington University': 'Wildcats',
  'Chaminade University of Honolulu': 'Silverswords',
  'Chestnut Hill College': 'Griffins',
  'Chowan University': 'Hawks',
  'Christian Brothers University': 'Buccaneers',
  'Claflin University': 'Panthers',
  'Clarion University of Pennsylvania': 'Golden Eagles',
  'Clark Atlanta University': 'Panthers',
  'Coker University': 'Cobras',
  'Colorado Christian University': 'Cougars',
  'Colorado Mesa University': 'Mavericks',
  'Colorado School of Mines': 'Orediggers',
  'Colorado State University – Pueblo': 'ThunderWolves',
  'Columbus State University': 'Cougars',
  'Concord University': 'Mountain Lions',
  'Concordia University – Irvine': 'Eagles',
  'Concordia University, St. Paul – Minnesota': 'Golden Bears',
  'D\'Youville University': 'Saints',
  'Davenport University': 'Panthers',
  'Davis & Elkins College': 'Senators',
  'Delta State University': 'Statesmen',
  'Dominican University – New York': 'Chargers',
  'Drury University': 'Panthers',
  'East Central University': 'Tigers',
  'East Stroudsburg University of Pennsylvania': 'Warriors',
  'Eastern New Mexico University': 'Greyhounds',
  'Eckerd College': 'Tritons',
  'Edward Waters University': 'Tigers',
  'Embry-Riddle Aeronautical University': 'Eagles',
  'Emmanuel University – Georgia': 'Lions',
  'Emory & Henry College': 'Wasps',
  'Emporia State University': 'Hornets',
  'Erskine College': 'Flying Fleet',
  'Fairmont State University': 'Falcons',
  'Felician University': 'Golden Falcons',
  'Flagler College – St. Augustine': 'Saints',
  'Florida Southern College': 'Moccasins',
  'Florida Tech': 'Panthers',
  'Fort Hays State University': 'Tigers',
  'Francis Marion University': 'Patriots',
  'Franklin Pierce University': 'Ravens',
  'Fresno Pacific University': 'Sunbirds',
  'Frostburg State University': 'Bobcats',
  'Gannon University': 'Golden Knights',
  'Georgia College & State University': 'Bobcats',
  'Georgia Southwestern State University': 'Hurricanes',
  'Georgian Court University': 'Lions',
  'Glenville State University': 'Pioneers',
  'Goldey-Beacom College': 'Lightning',
  'Grand Valley State University': 'Lakers',
  'Harding University': 'Bisons',
  'Hawaii Pacific University': 'Sharks',
  'Henderson State University': 'Reddies',
  'Hillsdale College': 'Chargers',
  'Holy Family University': 'Tigers',
  'Indiana University of Pennsylvania': 'Crimson Hawks',
  'Kentucky State University': 'Thorobreds',
  'Kentucky Wesleyan College': 'Panthers',
  'King University – Tennessee': 'Tornado',
  'Kutztown University of Pennsylvania': 'Golden Bears',
  'Lake Erie College': 'Storm',
  'Lander University': 'Bearcats',
  'Lane College': 'Dragons',
  'LeMoyne-Owen College': 'Magicians',
  'Lee University': 'Flames',
  'Lenoir-Rhyne University': 'Bears',
  'Lewis University': 'Flyers',
  'Lock Haven University': 'Bald Eagles',
  'Limestone University': 'Saints',
  'Lincoln Memorial University': 'Railsplitters',
  'Lincoln University Pennsylvania': 'Lions',
  'Lincoln University – Missouri': 'Blue Tigers',
  'Lubbock Christian University': 'Chaparrals',
  'Lynn University': 'Fighting Knights',
  'Malone University': 'Pioneers',
  'Mansfield University of Pennsylvania': 'Mounties',
  'Mars Hill University': 'Lions',
  'Maryville University': 'Saints',
  'McKendree University': 'Bearcats',
  'Menlo College': 'Oaks',
  'Mercy University': 'Mavericks',
  'Metropolitan State University of Denver': 'Roadrunners',
  'Miles College': 'Golden Bears',
  'Millersville University of Pennsylvania': 'Marauders',
  'Minnesota State University – Mankato': 'Mavericks',
  'Minot State University': 'Beavers',
  'Mississippi College': 'Choctaws',
  'Missouri Southern State University': 'Lions',
  'Missouri University of Science & Technology': 'Miners',
  'Missouri Western State University': 'Griffons',
  'Molloy University': 'Lions',
  'Montana State University – Billings': 'Yellowjackets',
  'Morehouse College': 'Maroon Tigers',
  'New Haven': 'Chargers',
  'New Mexico Highlands University': 'Cowboys',
  'Newberry College': 'Wolves',
  'Newman University': 'Jets',
  'North Greenville University': 'Crusaders',
  'Northeastern State University': 'Riverhawks',
  'Northern State University': 'Wolves',
  'Northwest Missouri State University': 'Bearcats',
  'Northwest Nazarene University': 'Nighthawks',
  'Northwestern Oklahoma State University': 'Rangers',
  'Northwood University – Michigan': 'Timberwolves',
  'Nova Southeastern University': 'Sharks',
  'Ohio Dominican University': 'Panthers',
  'Oklahoma Christian University': 'Eagles',
  'Ouachita Baptist University': 'Tigers',
  'Pace University': 'Setters',
  'Palm Beach Atlantic University': 'Sailfish',
  'Pittsburg State University': 'Gorillas',
  'Point Loma Nazarene University': 'Sea Lions',
  'Point Park University': 'Pioneers',
  'Post University': 'Eagles',
  'Purdue University – Northwest': 'Pride',
  'Quincy University': 'Hawks',
  'Regis University': 'Rangers',
  'Rockhurst University': 'Hawks',
  'Rogers State University': 'Hillcats',
  'Rollins College': 'Tars',
  'Roosevelt University': 'Lakers',
  'Saginaw Valley State University': 'Cardinals',
  'Saint Anselm College': 'Hawks',
  'Saint Leo University': 'Lions',
  'Saint Martin\'s University': 'Saints',
  'Saint Mary\'s College': 'Gaels',
  'Saint Michael\'s College': 'Purple Knights',
  'Salem University': 'Tigers',
  'San Francisco State University': 'Gators',
  'Savannah State University': 'Tigers',
  'Seton Hill University': 'Griffins',
  'Shepherd University': 'Rams',
  'Shippensburg University of Pennsylvania': 'Raiders',
  'Shorter University': 'Hawks',
  'Slippery Rock University': 'The Rock',
  'Sonoma State University': 'Seawolves',
  'Southern Arkansas University': 'Muleriders',
  'Southern Connecticut State University': 'Owls',
  'Southern Nazarene University': 'Crimson Storm',
  'Southern New Hampshire University': 'Penmen',
  'Southern Wesleyan University': 'Warriors',
  'Southwest Baptist University': 'Bearcats',
  'Southwest Minnesota State University': 'Mustangs',
  'Southwestern Oklahoma State University': 'Bulldogs',
  'Spring Hill College': 'Badgers',
  'St. Cloud State University': 'Huskies',
  'St. Edward\'s University': 'Hilltoppers',
  'St. Mary\'s University – Texas': 'Rattlers',
  'St. Thomas Aquinas College': 'Spartans',
  'Southeastern Oklahoma State University': 'Savage Storm',
  'Tarleton State': 'Texans',
  'Texas A&M International University': 'Dustdevils',
  'Texas A&M University – Kingsville': 'Javelinas',
  'The University of Virginia\'s College at Wise': 'Highland Cavaliers',
  'Thomas Jefferson University (Formerly Philadelphia University)': 'Rams',
  'Thomas More University': 'Saints',
  'Tiffin University': 'Dragons',
  'Trevecca Nazarene University': 'Trojans',
  'Truman State University': 'Bulldogs',
  'Tusculum University': 'Pioneers',
  'Tuskegee University': 'Golden Tigers',
  'Union University': 'Bulldogs',
  'University of Alabama – Huntsville': 'Chargers',
  'University of Arkansas at Monticello': 'Boll Weevils',
  'University of Arkansas – Fort Smith': 'Lions',
  'University of Bridgeport': 'Purple Knights',
  'University of Central Missouri': 'Mules',
  'University of Central Oklahoma': 'Bronchos',
  'University of Charleston': 'Golden Eagles',
  'University of Colorado – Colorado Springs': 'Mountain Lions',
  'University of Findlay': 'Oilers',
  'University of Hawaii at Hilo': 'Vulcans',
  'University of Illinois at Springfield': 'Prairie Stars',
  'University of Indianapolis': 'Greyhounds',
  'University of Jamestown': 'Jimmies',
  'University of Mary': 'Marauders',
  'University of Minnesota – Crookston': 'Golden Eagles',
  'University of Minnesota – Duluth': 'Bulldogs',
  'University of Missouri – St. Louis': 'Tritons',
  'University of Montevallo': 'Falcons',
  'University of Mount Olive': 'Trojans',
  'University of North Carolina at Pembroke': 'Braves',
  'University of North Georgia': 'Nighthawks',
  'University of Pittsburgh – Johnstown': 'Mountain Cats',
  'University of Sioux Falls': 'Cougars',
  'University of South Carolina Aiken': 'Pacers',
  'University of South Carolina – Beaufort': 'Sand Sharks',
  'University of Tampa': 'Spartans',
  'University of Texas – Permian Basin': 'Falcons',
  'University of Texas – Tyler': 'Patriots',
  'University of West Alabama': 'Tigers',
  'University of West Florida': 'Argonauts',
  'University of Wisconsin – Parkside': 'Rangers',
  'Upper Iowa University': 'Peacocks',
  'Valdosta State University': 'Blazers',
  'Virginia State University': 'Trojans',
  'Walsh University': 'Cavaliers',
  'Washburn University': 'Ichabods',
  'Wayne State College': 'Wildcats',
  'Wayne State University': 'Warriors',
  'West Chester University of Pennsylvania': 'Golden Rams',
  'West Georgia': 'Wolves',
  'West Liberty University': 'Hilltoppers',
  'West Texas A&M University': 'Buffaloes',
  'West Virginia State University': 'Yellow Jackets',
  'West Virginia Wesleyan College': 'Bobcats',
  'Western Oregon University': 'Wolves',
  'Westmont College': 'Warriors',
  'Wheeling University': 'Cardinals',
  'William Jessup University': 'Warriors',
  'William Jewell College': 'Cardinals',
  'Wilmington University': 'Wildcats',
  'Wingate University': 'Bulldogs',
  'Winona State University': 'Warriors',
  'Young Harris College': 'Mountain Lions',
};

/**
 * Retrieves the mascot for a given university.
 */
function getMascot(university) {
  return MASCOT_LOOKUP[university] || '';
}

/**
 * Build an optimized search query for a school.
 */
function buildSearchQuery(camp) {
  const mascot = getMascot(camp.university);
  if (mascot && !camp.university.toLowerCase().includes(mascot.toLowerCase())) {
    return `${camp.university} ${mascot} baseball camp 2026`;
  }
  return `${camp.university} baseball camp 2026`;
}

/**
 * Generates an array of potential name aliases for a university.
 */
function getUniversityAliases(university) {
  if (!university) return [];
  const aliases = new Set();
  const lower = university.toLowerCase();
  aliases.add(lower);

  // Mascot match
  const mascot = getMascot(university);
  if (mascot) {
    aliases.add(mascot.toLowerCase());
    if (mascot.endsWith('s')) aliases.add(mascot.substring(0, mascot.length - 1).toLowerCase());
  }

  // 1. Basic cleaning
  const clean = university
    .replace(/\bUniversity of\b/gi, '')
    .replace(/\bUniversity\b/gi, '')
    .replace(/\bState University\b/gi, '')
    .replace(/\bCollege of\b/gi, '')
    .replace(/\bCollege\b/gi, '')
    .replace(/\bState\b/gi, '')
    .trim();
  if (clean && clean.length > 2) aliases.add(clean.toLowerCase());

  // 2. Hyphenated splits
  if (university.includes('-')) {
    aliases.add(university.replace(/-/g, ' ').toLowerCase());
    const parts = university.split('-');
    const main = parts[0];
    const branch = parts[1];
    
    const stateShorts = {
      'Tennessee': ['UT', 'Tenn'],
      'Mississippi': ['UM', 'Miss'],
      'Alabama': ['AL', 'Bama'],
      'North Carolina': ['UNC'],
      'South Carolina': ['USC'], 
      'California': ['UC', 'Cal'],
      'Louisiana': ['UL'],
      'Arkansas': ['ASU', 'U of A', 'Ar']
    };

    const shortList = stateShorts[main];
    if (shortList) {
      shortList.forEach(s => {
        aliases.add(`${s} ${branch}`.toLowerCase());
        aliases.add(`${s}-${branch}`.toLowerCase());
        aliases.add(`${s}${branch}`.toLowerCase());
      });
    }
  }

  // 3. Special cases
  if (lower.startsWith('university of ')) {
    const state = lower.replace('university of ', '');
    const short = {
      'tennessee': 'ut',
      'north carolina': 'unc',
      'south carolina': 'usc',
      'california': 'uc',
      'colorado': 'cu',
      'florida': 'uf',
      'texas': 'ut'
    }[state];
    if (short) aliases.add(short);
  }

  // 4. Manually assigned acronyms
  const acronyms = {
    'LSU': ['Louisiana State'],
    'TCU': ['Texas Christian'],
    'USC': ['Southern California'],
    'UCLA': ['California Los Angeles'],
    'FGCU': ['Florida Gulf Coast'],
    'FAU': ['Florida Atlantic'],
    'FIU': ['Florida International'],
    'UCF': ['Central Florida'],
    'UIC': ['Illinois Chicago'],
    'UNCW': ['North Carolina Wilmington'],
    'UNCG': ['North Carolina Greensboro'],
    'UNLV': ['Nevada Las Vegas'],
    'VCU': ['Virginia Commonwealth'],
    'VMI': ['Virginia Military'],
    'NJIT': ['New Jersey Institute'],
    'UMBC': ['Maryland Baltimore County'],
    'UT Martin': ['Tennessee Martin', 'UTM'],
    'Little Rock': ['UALR', 'UA Little Rock'],
    'Truman State University': ['Truman']
  };

  if (acronyms[university]) {
    acronyms[university].forEach(a => aliases.add(a.toLowerCase()));
  }

  return Array.from(aliases).filter(a => a.length >= 2);
}

module.exports = { 
  MASCOT_LOOKUP, 
  getMascot, 
  buildSearchQuery, 
  getUniversityAliases 
};
